-- Latest transaction per device.
CREATE OR ALTER PROCEDURE dbo.SP_MOVEMENT_TRANSACTION_LATEST
    @PlantId INT = NULL
AS
BEGIN
    SET NOCOUNT ON;

    BEGIN TRY
        SELECT
            DEVICE_ID,
            MAX(COALESCE(TRANSACTION_DATE, CREATED_ON)) AS LAST_TRANSACTION_DATE
        FROM dbo.TBL_EQUIPMENT_TRANSACTION
        WHERE DEVICE_ID IS NOT NULL AND LTRIM(RTRIM(DEVICE_ID)) <> ''
        GROUP BY DEVICE_ID;
    END TRY
    BEGIN CATCH
        DECLARE @ErrMsg NVARCHAR(4000) = ERROR_MESSAGE();
        DECLARE @ErrNum INT = ERROR_NUMBER();
        RAISERROR('SP_MOVEMENT_TRANSACTION_LATEST failed (%d): %s', 16, 1, @ErrNum, @ErrMsg);
    END CATCH
END;
