-- Get a transaction by ID.
CREATE OR ALTER PROCEDURE dbo.SP_MOVEMENT_TRANSACTION_GET
    @TransactionId INT,
    @PlantId INT = NULL
AS
BEGIN
    SET NOCOUNT ON;

    BEGIN TRY
        SELECT *
        FROM dbo.TBL_EQUIPMENT_TRANSACTION
        WHERE TRANSACTION_ID = @TransactionId;
    END TRY
    BEGIN CATCH
        DECLARE @ErrMsg NVARCHAR(4000) = ERROR_MESSAGE();
        DECLARE @ErrNum INT = ERROR_NUMBER();
        RAISERROR('SP_MOVEMENT_TRANSACTION_GET failed (%d): %s', 16, 1, @ErrNum, @ErrMsg);
    END CATCH
END;
