IF OBJECT_ID('dbo.TBL_MST_PLANT', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.TBL_MST_PLANT (
        PLANT_ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
        PLANT_CODE NVARCHAR(50) NULL,
        PLANT_NAME NVARCHAR(150) NOT NULL,
        LOCATION NVARCHAR(250) NULL,
        IS_ACTIVE BIT NOT NULL CONSTRAINT DF_TBL_MST_PLANT_IS_ACTIVE DEFAULT (1),
        IS_DELETED BIT NOT NULL CONSTRAINT DF_TBL_MST_PLANT_IS_DELETED DEFAULT (0),
        CREATED_BY INT NULL,
        CREATED_DATE DATETIME NOT NULL CONSTRAINT DF_TBL_MST_PLANT_CREATED_DATE DEFAULT (GETDATE()),
        MODIFIED_BY INT NULL,
        MODIFIED_DATE DATETIME NULL
    );
END;

IF COL_LENGTH('dbo.TBL_MST_ROLE', 'PLANT_ID') IS NULL
BEGIN
    ALTER TABLE dbo.TBL_MST_ROLE
    ADD PLANT_ID INT NULL;
END;

IF NOT EXISTS (
    SELECT 1
    FROM sys.foreign_keys
    WHERE name = 'FK_TBL_MST_ROLE_TBL_MST_PLANT'
)
BEGIN
    ALTER TABLE dbo.TBL_MST_ROLE
    ADD CONSTRAINT FK_TBL_MST_ROLE_TBL_MST_PLANT
    FOREIGN KEY (PLANT_ID) REFERENCES dbo.TBL_MST_PLANT(PLANT_ID);
END;
